//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.workflowconcepts.applications.uccx.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.workflowconcepts.applications.uccx.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;callback&gt;
        ///  &lt;csqs&gt;
        ///    &lt;csq name=&quot;Default&quot;&gt;
        ///
        ///      &lt;CallbackEnabled&gt;false&lt;/CallbackEnabled&gt;
        ///      &lt;CallerRecording&gt;false&lt;/CallerRecording&gt;
        ///      &lt;RetentionPeriod&gt;7&lt;/RetentionPeriod&gt;
        ///      &lt;AppServerURLPrefix&gt;@CALLBACKSERVERAPI@&lt;/AppServerURLPrefix&gt;
        ///      &lt;EmailAlerts&gt;false&lt;/EmailAlerts&gt;
        ///      &lt;AdminEmail&gt;&lt;/AdminEmail&gt;
        ///      &lt;CallerIDVerify&gt;false&lt;/CallerIDVerify&gt;
        ///      &lt;AbandonCallback&gt;false&lt;/AbandonCallback&gt;
        ///      &lt;AbandonCBMinQTime&gt;120&lt;/AbandonCBMinQTim [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Callback_Settings {
            get {
                return ResourceManager.GetString("Callback_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gtk_refresh {
            get {
                object obj = ResourceManager.GetObject("gtk_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;response&gt;
        ///  &lt;code&gt;0&lt;/code&gt;
        ///  &lt;description/&gt;
        ///  &lt;contacts&gt;
        ///    &lt;contact&gt;
        ///      &lt;contactid&gt;26270&lt;/contactid&gt;
        ///      &lt;type&gt;Cisco JTAPI Call&lt;/type&gt;
        ///      &lt;implid&gt;12394666/2&lt;/implid&gt;
        ///      &lt;starttime&gt;10:57:53&lt;/starttime&gt;
        ///      &lt;duration&gt;0:2:49&lt;/duration&gt;
        ///      &lt;application&gt;Operations-FM&lt;/application&gt;
        ///      &lt;task&gt;39000866968&lt;/task&gt;
        ///      &lt;session&gt;76000330007&lt;/session&gt;
        ///      &lt;queuedfor&gt;[STRDA1]]&lt;/queuedfor&gt;
        ///    &lt;/contact&gt;
        ///    &lt;contact&gt;
        ///      &lt;c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RealtimeContactData {
            get {
                return ResourceManager.GetString("RealtimeContactData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Workflow_Concepts_logo {
            get {
                object obj = ResourceManager.GetObject("Workflow_Concepts_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
